### PR TITLE
Fix repo name in publish command

### PR DESCRIPTION
**Pull request by wemrysi**

### CODE REVIEW

**Review by rintcius — APPROVED** [review]
👍 

Just checking, did you register the repos in bintray too?

**Comment by wemrysi** [comment]
@rintcius hm, I don't remember ever having to register a repo in bintray, what needs to be done?

**Comment by rintcius** [comment]
@wemrysi I have encountered that it won't publish without it, but we can just merge and find out what happens now :)

**Comment by djspiewak** [comment]
@rintcius It only fails with snapshot publication. I need to just, fix `releaseSnapshot`. The actual full release command works fine.

**Pull request merged**
