### PR TITLE
Destination support

### PR DESCRIPTION
**Pull request by wemrysi**
Adds support for quasar destinations, rename to `sbt-quasar-plugin`.

[ch9067]

### CODE REVIEW

**Comment by wemrysi** [comment]
I'll rename the repo once this is merged.

**Comment by rintcius** [comment]
@wemrysi did you see https://github.com/slamdata/sbt-quasar-destination/pull/1 ?
I prefer this PR since it saves us a bit of duplication and an extra repos, but good to check with @djspiewak 

BTW I was also thinking that in the future we can get rid of this repos completely if we add support to launcher to specify local plugins

**Comment by wemrysi** [comment]
@rintcius I did not see `sbt-quasar-destination`, but I still think I prefer this due, as you mentioned, to reduction in duplication and making it easier to support both source and destination in the same plugin.

As for omitting it completely, I think it still has value regardless of launcher support as we need to specify jar manifest attributes and also for building plugins to use in development (e.g. running a local repl via `sbt` to leverage source evictions).

**Comment by djspiewak** [comment]
This is indeed better than mine

**Review by rintcius — APPROVED** [review]
Looks good to me 👍

**Comment by rintcius** [comment]
@wemrysi Right, it is useful for the jar manifest.

I think there's some overlap in functionality though, that we should get rid of (e.g. the coursier code that fetches the deps). Maybe `fetcher` is the right place for that, if we reverse the dep between `fetcher` and `launcher`? Then this repos can also depend on `fetcher`.

**Comment by wemrysi** [comment]
@rintcius Ah, yeah, being able to depend on `fetcher` would be great :+1:

**Pull request merged**
